disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Jurnalamm"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Jurnalamm: Notes on nature and tech"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Rafli Hadiana"
  image = "img/rafli-photos.jpg"
  imageQuality = 96
  headline = "Cloud Engineer & FOSS Enthusiast"
  bio = "Passionate about <strong>cloud-native</strong> technologies, <strong>Kubernetes</strong>, and <strong>5G/Future Networks</strong>. When I'm not working, I'm trail running through mountains, traveling, or writing about life. This is my creative space to express ideas. <strong>#livin'aquitelife</strong>"
  links = [
    { email = "mailto:raflihadian24@gmail.com" },
    { github = "https://github.com/raflihadiana" },
    { linkedin = "https://linkedin.com/in/raflihadiana" },
    { medium = "https://medium.com/@raflihadiana" },
    { instagram = "https://instagram.com/raflihadiana" },
  ]
